# Generated by Django 5.2.6 on 2025-11-07 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jwellery', '0003_wishlist'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={},
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
